name: build
on:
  push:
    branches: [ "master" , "develop" , "main" ]
  pull_request:
    branches: [ "master" ,"develop", "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
